/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class at_uniklu_itec_videosummary_InvokeGist */

#ifndef _Included_at_uniklu_itec_videosummary_InvokeGist
#define _Included_at_uniklu_itec_videosummary_InvokeGist
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     at_uniklu_itec_videosummary_InvokeGist
 * Method:    computeGist
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_at_uniklu_itec_videosummary_InvokeGist_computeGist
  (JNIEnv *, jobject, jstring, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
